acces_ouverts = {
	'wphuISEV': {'page': 'apprenant', 'salon': 0},
	'O7Tj9swu': {'page': 'apprenant', 'salon': 1},
	'D0SO1WHy': {'page': 'apprenant', 'salon': 2},
	'Vz08EiVD': {'page': 'apprenant', 'salon': 3},
	'Qu8iBigk': {'page': 'apprenant', 'salon': 4},
	'7AI496Jd': {'page': 'apprenant', 'salon': 5},
	'48b6XvGz': {'page': 'apprenant', 'salon': 6},
	'Vuc50a3n': {'page': 'apprenant', 'salon': 7},
	'vHUKmw1E': {'page': 'enseignant', 'salon': 0},
	'rVClfxyp': {'page': 'enseignant', 'salon': 1},
	'z2IbUNLo': {'page': 'enseignant', 'salon': 2},
	'REpFbgHw': {'page': 'enseignant', 'salon': 3},
	'LLRq5wJs': {'page': 'enseignant', 'salon': 4},
	'oAz9Qnc6': {'page': 'enseignant', 'salon': 5},
	'NQlYoJ2Z': {'page': 'enseignant', 'salon': 6},
	'hKNMOAS8': {'page': 'enseignant', 'salon': 7},
	'test-apprenant': {'page': 'apprenant', 'salon': 8},
	'test-enseignant': {'page': 'enseignant', 'salon': 8},
	'B2b': {'page': 'apprenant', 'salon': 9},
	'BdEHFvORGRcSXyeVtabWfQeXzsCDOJSIfpPbISQOmmrJVdmBeQHbEwvNUuQGUzGEcVgsDxoMYcujpQmjRpyBmQVInGzJjhAvDsngTTPqHTPIgmgefoShCmBgQYUqdbAQ': {'page': 'enseignant', 'salon': 9},
}
salons = [
	{'nom_salon': 'Groupe C1a', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe C1b', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe C2a', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe C2b', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe D1a', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe D1b', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe D2a', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe D2b', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Salon de test', 'apprenants': {}, 'liste_assistances': []},
	{'nom_salon': 'Groupe B2b', 'apprenants': {}, 'liste_assistances': []},
]
